# Generated by Django 3.2.10 on 2022-09-03 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='fullname',
            new_name='FirstName',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='email',
        ),
        migrations.AddField(
            model_name='queries',
            name='DoB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='LastName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queries',
            name='reply',
            field=models.TextField(blank=True, default='Please wait for the response', null=True),
        ),
        migrations.AddField(
            model_name='queries',
            name='send_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
