# Generated by Django 3.2.10 on 2023-01-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PBirth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vaccines',
            name='Vaxplace',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
