# Generated by Django 4.1.1 on 2022-09-12 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prebirth', models.BooleanField(default=False)),
                ('Birth', models.BooleanField(default=False)),
                ('SixWeeks', models.BooleanField(default=False)),
                ('TenWeeeks', models.BooleanField(default=False)),
                ('FourteenWeeks', models.BooleanField(default=False)),
                ('Ninemonths', models.BooleanField(default=False)),
                ('Fifteenmonths', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
