# Generated by Django 3.2.10 on 2023-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230102_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='typee',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
