# Generated by Django 4.1.1 on 2022-09-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='Prebirth',
        ),
    ]
