# Generated by Django 4.1.1 on 2022-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vaccines'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='Vaxplace',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
