# Generated by Django 3.2.10 on 2022-12-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_vaccines_vaxplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PBirth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
