# Generated by Django 4.1.1 on 2022-09-12 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_vaccines_prebirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='send_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
