# Generated by Django 4.1.1 on 2022-09-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_vaccines_send_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccines',
            old_name='send_at',
            new_name='added_at',
        ),
    ]
