# Generated by Django 3.2.10 on 2023-01-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_typee'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='KG',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
