# Generated by Django 4.1.1 on 2022-09-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_send_at_vaccines_added_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccines',
            name='Birth',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='Fifteenmonths',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='FourteenWeeks',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='Ninemonths',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='SixWeeks',
        ),
        migrations.RemoveField(
            model_name='vaccines',
            name='TenWeeeks',
        ),
        migrations.AddField(
            model_name='vaccines',
            name='Vaxtype',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
